### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by cparello** [huffpostdata/python-pollster#12]
python pollster.py
Traceback (most recent call last):
  File "pollster.py", line 4, in <module>
    import pollster
  File "/var/www/python/pollster.py", line 5, in <module>
    from pollster.rest import ApiException
ImportError: No module named rest

**Comment by adamhooper** [comment]
Hi there,

Please provide a lot more information. What are the contents of pollster.py? What system are you on? What version of the "pollster" package are you using? How did you install it?

Here's what I did on a fresh Fedora 28 installation:

```python
pip3 install --user pollster
python3 -c 'import pollster; print(pollster.rest)'
# output: <module 'pollster.rest' from '/home/adam/.local/lib/python3.6/site-packages/pollster/rest.py'>
```
